In [28]:
import numpy as np
from time import time
import helpers

np.set_printoptions(linewidth=100)

# Problem 8
The four adjacent digits in the huge number with the largest product are $ 9 \times 9 \times 8 \times 9 = 5832$. Find the 13 adjacent digits with the largest product.

In [2]:
huge_num = "73167176531330624919225119674426574742"
huge_num += "3553491949349698352031277450632623957831801698480186947" 
huge_num += "88518438586156078911294949545950173795833195285320880551"
huge_num += "112540698747158523863050715693290963295227443043557668966"
huge_num += "4895044524452316173185640309871112172238311362229893423380"
huge_num += "3081353362766142828064444866452387493035890729629049156044077"
huge_num += "23907138105158593079608667017242712188399879790879227492190169"
huge_num += "972088809377665727333001053367881220235421809751254540594752243"
huge_num += "525849077116705560136048395864467063244157221553975369781797784617"
huge_num += "4064955149290862569321978468622482839722413756570560574902614079729"
huge_num += "68652414535100474821663704844031998900088952434506585412275886668811"
huge_num += "642717147992444292823086346567481391912316282458617866458359124566529"
huge_num += "4765456828489128831426076900422421902267105562632111110937054421750694"
huge_num += "165896040807198403850962455444362981230987879927244284909188845801561660979"
huge_num += "19133875499200524063689912560717606058861164671094050775410022569831552000559"
huge_num += "3572972571636269561882670428252483600823257530420752963450"

In [3]:
huge_num

'731671765313306249192251196744265747423553491949349698352031277450632623957831801698480186947885184385861560789112949495459501737958331952853208805511125406987471585238630507156932909632952274430435576689664895044524452316173185640309871112172238311362229893423380308135336276614282806444486645238749303589072962904915604407723907138105158593079608667017242712188399879790879227492190169972088809377665727333001053367881220235421809751254540594752243525849077116705560136048395864467063244157221553975369781797784617406495514929086256932197846862248283972241375657056057490261407972968652414535100474821663704844031998900088952434506585412275886668811642717147992444292823086346567481391912316282458617866458359124566529476545682848912883142607690042242190226710556263211111093705442175069416589604080719840385096245544436298123098787992724428490918884580156166097919133875499200524063689912560717606058861164671094050775410022569831552000559357297257163626956188267042825248360082325753042075296345

In [4]:
def compute_prod(n):
    num_facs = len(n)
    n = int(n)
    prod = 1.0
    facs = []
    for _ in range(num_facs):
        facs.append(n % 10)
        prod = prod * (n % 10)
        n = int(n / 10)
    return prod, facs

In [5]:
start_time = time()
i = 0
j = 4
n = huge_num[i:j]
product, factors = compute_prod(n)

while j <= len(huge_num):
    i += 1
    j += 1
    n = huge_num[i:j]
    temp_prod, temp_facs = compute_prod(n)
    if temp_prod > product:
        product = temp_prod
        factors = temp_facs
print('PROD({}) = {}'.format(factors, product))
print('This took {} secs to run'.format(time() - start_time))

PROD([9, 8, 9, 9]) = 5832.0
This took 0.0030889511108398438 secs to run


In [6]:
start_time = time()
i = 0
j = 13
n = huge_num[i:j]
product, factors = compute_prod(n)

while j <= len(huge_num):
    i += 1
    j += 1
    n = huge_num[i:j]
    temp_prod, temp_facs = compute_prod(n)
    if temp_prod > product:
        product = temp_prod
        factors = temp_facs
print('PROD({}) = {}'.format(factors, product))
print('This took {} secs to run'.format(time() - start_time))

PROD([5, 9, 8, 4, 6, 6, 9, 8, 6, 6, 7, 5, 5]) = 23514624000.0
This took 0.006891965866088867 secs to run


# Problem 9
Find $a \times b \times c$ where $a,b,c \in \mathbb{N}$ and $a^2 + b^2 = c^2$ and $a + b + c = 1000$.

In [7]:
def get_abc(b):
    a = (500000 - 1000 * b) / (1000 - b)
    c = 1000 - (a + b)
    return a, b, c

def is_int(x):
    if x - int(x) != 0:
        return False
    else:
        return True

In [8]:
start_time = time()
for blah in range(100, 1000):
    a, b, c = get_abc(blah)
    if is_int(a) and is_int(b) and is_int(c) and a*b*c > 0:
        print('a={}, b={}, c={}'.format(a, b, c))
print('This took {} secs to run'.format(time() - start_time))

a=375.0, b=200, c=425.0
a=200.0, b=375, c=425.0
This took 0.001445770263671875 secs to run


In [9]:
A, B, C = 200, 375, 425
print('A^2 + B^2 = {} + {} = {}'.format(A**2, B**2, A**2 + B**2))
print('C^2 = {}'.format(C**2))
print('A + B + C = {} + {} + {} = {}'.format(A, B, C, A + B + C))
print('The product of the triple is = {}*{}*{}={}'.format(A, B, C, A*B*C))

A^2 + B^2 = 40000 + 140625 = 180625
C^2 = 180625
A + B + C = 200 + 375 + 425 = 1000
The product of the triple is = 200*375*425=31875000


# Problem 10
The sum of the primes less than 10 is $2 + 3 + 5 + 7 = 17$. What is the sum of the primes less than 2,000,000?

In [15]:
primes_lt_2mm = helpers.seive(2000000)

In [16]:
print('Sum of primes below 2MM = {}'.format(np.sum(primes_lt_2mm)))

Sum of primes below 2MM = 142913828922


# Problem 11
Find the greatest product of four adjacent numbers in the grid in any direction (up, down, left, right, or diagonal).

In [23]:
grid_str = """08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72
21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95
78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48"""

In [24]:
GRID = []
for l in grid_str.split('\n'):
    row = l.split(' ')
    row = [int(el) for el in row]
    GRID.append(row)
GRID = np.array(GRID)

In [29]:
GRID

array([[ 8,  2, 22, 97, 38, 15,  0, 40,  0, 75,  4,  5,  7, 78, 52, 12, 50, 77, 91,  8],
       [49, 49, 99, 40, 17, 81, 18, 57, 60, 87, 17, 40, 98, 43, 69, 48,  4, 56, 62,  0],
       [81, 49, 31, 73, 55, 79, 14, 29, 93, 71, 40, 67, 53, 88, 30,  3, 49, 13, 36, 65],
       [52, 70, 95, 23,  4, 60, 11, 42, 69, 24, 68, 56,  1, 32, 56, 71, 37,  2, 36, 91],
       [22, 31, 16, 71, 51, 67, 63, 89, 41, 92, 36, 54, 22, 40, 40, 28, 66, 33, 13, 80],
       [24, 47, 32, 60, 99,  3, 45,  2, 44, 75, 33, 53, 78, 36, 84, 20, 35, 17, 12, 50],
       [32, 98, 81, 28, 64, 23, 67, 10, 26, 38, 40, 67, 59, 54, 70, 66, 18, 38, 64, 70],
       [67, 26, 20, 68,  2, 62, 12, 20, 95, 63, 94, 39, 63,  8, 40, 91, 66, 49, 94, 21],
       [24, 55, 58,  5, 66, 73, 99, 26, 97, 17, 78, 78, 96, 83, 14, 88, 34, 89, 63, 72],
       [21, 36, 23,  9, 75,  0, 76, 44, 20, 45, 35, 14,  0, 61, 33, 97, 34, 31, 33, 95],
       [78, 17, 53, 28, 22, 75, 31, 67, 15, 94,  3, 80,  4, 62, 16, 14,  9, 53, 56, 92],
       [16, 39,  5, 4

In [30]:
GRID.shape

(20, 20)

In [33]:
GRID[0:4, 0:4]

array([[ 8,  2, 22, 97],
       [49, 49, 99, 40],
       [81, 49, 31, 73],
       [52, 70, 95, 23]])

In [65]:
def get_products(mini_mat):
    row_prod = 1.0
    col_prod = 1.0
    dia_prod1 = 1.0
    dia_prod2 = 1.0
    for idx in range(mini_mat.shape[0]):
        row_prod = row_prod * mini_mat[0, idx]
        col_prod = col_prod * mini_mat[idx, 0]
        dia_prod1 = dia_prod1 * mini_mat[idx, idx]
        dia_prod2 = dia_prod2 * mini_mat[idx, 3 - idx]
    return row_prod, col_prod, dia_prod1, dia_prod2

In [66]:
def find_max_product(matrix):
    final_prod = -1.0
    for i in range(0, matrix.shape[0] - 3):
        for j in range(0, matrix.shape[1] - 3):
            temp_prod = np.max(get_products(matrix[i:i+4, j:j+4]))
            if temp_prod > final_prod:
                final_prod = temp_prod
    return final_prod

In [67]:
print(GRID)

[[ 8  2 22 97 38 15  0 40  0 75  4  5  7 78 52 12 50 77 91  8]
 [49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48  4 56 62  0]
 [81 49 31 73 55 79 14 29 93 71 40 67 53 88 30  3 49 13 36 65]
 [52 70 95 23  4 60 11 42 69 24 68 56  1 32 56 71 37  2 36 91]
 [22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80]
 [24 47 32 60 99  3 45  2 44 75 33 53 78 36 84 20 35 17 12 50]
 [32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70]
 [67 26 20 68  2 62 12 20 95 63 94 39 63  8 40 91 66 49 94 21]
 [24 55 58  5 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72]
 [21 36 23  9 75  0 76 44 20 45 35 14  0 61 33 97 34 31 33 95]
 [78 17 53 28 22 75 31 67 15 94  3 80  4 62 16 14  9 53 56 92]
 [16 39  5 42 96 35 31 47 55 58 88 24  0 17 54 24 36 29 85 57]
 [86 56  0 48 35 71 89  7  5 44 44 37 44 60 21 58 51 54 17 58]
 [19 80 81 68  5 94 47 69 28 73 92 13 86 52 17 77  4 89 55 40]
 [ 4 52  8 83 97 35 99 16  7 97 57 32 16 26 26 79 33 27 98 66]
 [88 36 68 87 57 62 20 72  3 46 33 67 46 55 12 32 63 93

In [69]:
# start_time = time()
# ctr = 0
# for i in range(0, GRID.shape[0] - 3):
#     for j in range(0, GRID.shape[1] - 3):
#         temp_grid = GRID[i:i+4, j:j+4]
#         ctr += 1
#         print('{}, {}'.format(temp_grid, get_products(temp_grid)))
#         #print(ctr)
# print('This took {} secs to run'.format(time() - start_time))

In [70]:
start_time = time()
big_ass_product = find_max_product(GRID)
print('The max product is {} and took {} secs to run'.format(big_ass_product, time() - start_time))

The max product is 70600674.0 and took 0.008266925811767578 secs to run
